# Generated by Django 4.2.1 on 2023-06-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog_section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_pg_blog_img', models.ImageField(upload_to='static/images/blog_img', verbose_name='Front Page Car Photo')),
                ('blog_front_pg_img', models.ImageField(upload_to='static/images/blog_img', verbose_name='Blog Page Car Photo')),
                ('title_blog', models.CharField(max_length=100)),
                ('date_field', models.DateField(default='June 08, 2023')),
                ('blog_para', models.CharField(max_length=2000)),
                ('author_name', models.CharField(max_length=80)),
                ('about_author', models.CharField(max_length=660)),
                ('user_name', models.CharField(max_length=80)),
                ('user_comment', models.CharField(max_length=500)),
            ],
        ),
    ]
