# Generated by Django 4.2.1 on 2023-06-08 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_blog_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_section',
            name='user_comment',
        ),
        migrations.RemoveField(
            model_name='blog_section',
            name='user_name',
        ),
    ]
