# Generated by Django 4.2.1 on 2023-06-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_remove_blog_section_blog_front_pg_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_section',
            name='date_field',
            field=models.DateField(),
        ),
    ]
