# Generated by Django 4.2.1 on 2023-06-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_alter_blog_section_date_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_section',
            name='blog_tag',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
