# Generated by Django 4.2.1 on 2023-06-12 12:26

import django.core.validators
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_alter_car_service_about_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car_service',
            name='Pmonthly_price',
        ),
        migrations.RemoveField(
            model_name='car_service',
            name='Prental_overview_2',
        ),
        migrations.RemoveField(
            model_name='car_service',
            name='Pweekly_price',
        ),
        migrations.AddField(
            model_name='car_service',
            name='Automatic_Headlights',
            field=models.CharField(choices=[('✅', '✅'), ('❌', '❌')], default='✅', max_length=10),
        ),
        migrations.AddField(
            model_name='car_service',
            name='Baggage',
            field=models.CharField(choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='2', max_length=4, verbose_name='Baggage'),
        ),
        migrations.AddField(
            model_name='car_service',
            name='Blind_Spot_Assist',
            field=models.CharField(choices=[('✅', '✅'), ('❌', '❌')], default='✅', max_length=10),
        ),
        migrations.AddField(
            model_name='car_service',
            name='Bluethooth_Audio',
            field=models.CharField(choices=[('✅', '✅'), ('❌', '❌')], default='✅', max_length=10),
        ),
        migrations.AddField(
            model_name='car_service',
            name='Engine_name',
            field=models.CharField(default='v8', max_length=50, verbose_name='Engine Name'),
        ),
        migrations.AddField(
            model_name='car_service',
            name='Horse_power',
            field=models.IntegerField(default=0, verbose_name='Horse Power'),
        ),
        migrations.AddField(
            model_name='car_service',
            name='Power_Liftgate',
            field=models.CharField(choices=[('✅', '✅'), ('❌', '❌')], default='✅', max_length=10),
        ),
        migrations.AddField(
            model_name='car_service',
            name='Rain_Sensing_Wipers',
            field=models.CharField(choices=[('✅', '✅'), ('❌', '❌')], default='✅', max_length=10),
        ),
        migrations.AddField(
            model_name='car_service',
            name='Rearview_Camera',
            field=models.CharField(choices=[('✅', '✅'), ('❌', '❌')], default='✅', max_length=10),
        ),
        migrations.AddField(
            model_name='car_service',
            name='car_doors',
            field=models.CharField(choices=[('2', '2'), ('3', '3'), ('4', '4')], default='2', max_length=4, verbose_name='Car doors'),
        ),
        migrations.AddField(
            model_name='car_service',
            name='color',
            field=models.CharField(default='Black', max_length=50, verbose_name='Car color'),
        ),
        migrations.AlterField(
            model_name='car_service',
            name='About_item',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(640)], verbose_name='About item'),
        ),
        migrations.AlterField(
            model_name='car_service',
            name='Prental_overview_1',
            field=tinymce.models.HTMLField(verbose_name='Rental overview'),
        ),
        migrations.AlterField(
            model_name='car_service',
            name='people_sitting',
            field=models.CharField(choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], default='2', max_length=4, verbose_name='People sitting'),
        ),
    ]
