# Generated by Django 4.2.1 on 2023-06-12 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_car_service_transmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_service',
            name='transmission',
            field=models.CharField(default='ZF 8-speed', max_length=50, verbose_name='Transmission'),
        ),
    ]
