# Generated by Django 4.2.1 on 2023-06-12 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_alter_car_service_transmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='car_service',
            name='top_speed',
            field=models.IntegerField(default=0, verbose_name='Top Speed'),
        ),
    ]
