# Generated by Django 4.2.1 on 2023-06-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_car_service_top_speed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_service',
            name='car_doors',
            field=models.CharField(choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='2', max_length=4, verbose_name='Car doors'),
        ),
    ]
