# Generated by Django 4.2.1 on 2023-06-13 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0015_rename_year_car_service_model_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_service',
            name='automatic',
            field=models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual'), ('Automatic or Manual', 'Automatic or Manual')], max_length=50),
        ),
    ]
