# Generated by Django 4.2.1 on 2023-06-15 11:48

from django.db import migrations, models
import service.models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0016_alter_car_service_automatic'),
    ]

    operations = [
        migrations.AddField(
            model_name='car_service',
            name='car_image_10',
            field=models.ImageField(blank=True, upload_to=service.models.get_upload_path_product),
        ),
        migrations.AddField(
            model_name='car_service',
            name='car_image_11',
            field=models.ImageField(blank=True, upload_to=service.models.get_upload_path_product),
        ),
        migrations.AddField(
            model_name='car_service',
            name='car_image_8',
            field=models.ImageField(blank=True, upload_to=service.models.get_upload_path_product),
        ),
        migrations.AddField(
            model_name='car_service',
            name='car_image_9',
            field=models.ImageField(blank=True, upload_to=service.models.get_upload_path_product),
        ),
    ]
