# Generated by Django 4.2.1 on 2023-06-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0017_car_service_car_image_10_car_service_car_image_11_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_section',
            name='Auth_img',
            field=models.ImageField(default='No information available', upload_to='Author_pics', verbose_name='Author Images'),
        ),
        migrations.AlterField(
            model_name='blog_section',
            name='front_pg_blog_img',
            field=models.ImageField(upload_to='blog_img', verbose_name='Front Page Car Photo'),
        ),
    ]
